# **Limpieza de Datos**

### **Por:**

*   Yasmin Judith Florez Zabala
*   John Jairo Sevilla Rodriguez
*   Yulexa Andrea Aragón Lemus

In [ ]:
from scipy.io import arff
import pandas as pd

# Se lee el archivo ARFF
data, meta = arff.loadarff('sabana_hembras_porcinas_preparado.arff')

# Se convierte a DataFrame
df = pd.DataFrame(data)

# Se decodifica todas las columnas tipo objeto
for col in df.select_dtypes([object]).columns:
    df[col] = df[col].str.decode('utf-8')

df.head(3)

,GRANJA,NUMERO_PARTO,RAZA,EDAD_CERDA_DIAS,DIAS_EN_GRANJA,PESO_AL_SERVICIO,DIAS_DESTETE_SERVICIO,INTENTOS_INSEMINACION_ANTERIOR,DIAS_GESTACION_ANTERIOR,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,TOTAL_MOMIAS_ANTERIORES,ABORTOS_ACUMULADOS,RETORNOS_ACUMULADOS,NO_PRENADAS_ACUMULADAS,PARTO_EXITOSO
0,Granja 203,4.0,CAMBOROUGH,758.0,649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NO_EXITOSO
1,Granja 88,7.0,CAMBOROUGH,1192.0,960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,EXITOSO
2,Granja 88,8.0,CAMBOROUGH,1333.0,1101.0,NaN,5.0,NaN,NaN,16.0,1.0,0.0,0.0,0.0,0.0,NO_EXITOSO

In [ ]:
# Se eliminan las razas inválidas
df = df[~df["RAZA"].isin(["SIN_ASIGNAR"])]
df.head(3)

,GRANJA,NUMERO_PARTO,RAZA,EDAD_CERDA_DIAS,DIAS_EN_GRANJA,PESO_AL_SERVICIO,DIAS_DESTETE_SERVICIO,INTENTOS_INSEMINACION_ANTERIOR,DIAS_GESTACION_ANTERIOR,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,TOTAL_MOMIAS_ANTERIORES,ABORTOS_ACUMULADOS,RETORNOS_ACUMULADOS,NO_PRENADAS_ACUMULADAS,PARTO_EXITOSO
0,Granja 203,4.0,CAMBOROUGH,758.0,649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NO_EXITOSO
1,Granja 88,7.0,CAMBOROUGH,1192.0,960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,EXITOSO
2,Granja 88,8.0,CAMBOROUGH,1333.0,1101.0,NaN,5.0,NaN,NaN,16.0,1.0,0.0,0.0,0.0,0.0,NO_EXITOSO

In [ ]:
# Se reemplazan por valores nulos los registros considerados atípicos o inconsistentes según límites máximos definidos para cada variable
df.loc[df["EDAD_CERDA_DIAS"] > 2500, "EDAD_CERDA_DIAS"] = None
df.loc[df["DIAS_EN_GRANJA"] > 2500, "DIAS_EN_GRANJA"] = None
df.loc[df["PESO_AL_SERVICIO"] > 300, "PESO_AL_SERVICIO"] = None
df.loc[df["DIAS_DESTETE_SERVICIO"] > 60, "DIAS_DESTETE_SERVICIO"] = None
df.loc[df["DIAS_GESTACION_ANTERIOR"] > 130, "DIAS_GESTACION_ANTERIOR"] = None
df.head(3)

,GRANJA,NUMERO_PARTO,RAZA,EDAD_CERDA_DIAS,DIAS_EN_GRANJA,PESO_AL_SERVICIO,DIAS_DESTETE_SERVICIO,INTENTOS_INSEMINACION_ANTERIOR,DIAS_GESTACION_ANTERIOR,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,TOTAL_MOMIAS_ANTERIORES,ABORTOS_ACUMULADOS,RETORNOS_ACUMULADOS,NO_PRENADAS_ACUMULADAS,PARTO_EXITOSO
0,Granja 203,4.0,CAMBOROUGH,758.0,649.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,NO_EXITOSO
1,Granja 88,7.0,CAMBOROUGH,1192.0,960.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,EXITOSO
2,Granja 88,8.0,CAMBOROUGH,1333.0,1101.0,NaN,5.0,NaN,NaN,16.0,1.0,0.0,0.0,0.0,0.0,NO_EXITOSO

In [ ]:
# Se crea una nueva columna que almacena la cantidad de valores nulos presentes en cada registro del DataFrame
df['total_nulos'] = df.isnull().sum(axis=1)

In [ ]:
# Se eliminan los registros con más del 15% de nulos (más de 2 nulos)
df = df[df['total_nulos'] <= 2]
df = df.drop(columns=['total_nulos'])
df.head()

,GRANJA,NUMERO_PARTO,RAZA,EDAD_CERDA_DIAS,DIAS_EN_GRANJA,PESO_AL_SERVICIO,DIAS_DESTETE_SERVICIO,INTENTOS_INSEMINACION_ANTERIOR,DIAS_GESTACION_ANTERIOR,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,TOTAL_MOMIAS_ANTERIORES,ABORTOS_ACUMULADOS,RETORNOS_ACUMULADOS,NO_PRENADAS_ACUMULADAS,PARTO_EXITOSO
5,Granja 20,6.0,CAMBOROUGH,1066.0,921.0,NaN,3.0,1.0,116.0,14.000,2.0,2.0,0.0,0.0,0.0,EXITOSO
6,Granja 20,7.0,CAMBOROUGH,1202.0,1057.0,NaN,3.0,1.0,113.0,14.000,5.0,2.0,0.0,0.0,0.0,NO_EXITOSO
7,Granja 20,8.0,CAMBOROUGH,1341.0,1196.0,NaN,5.0,1.0,116.0,13.750,6.0,2.0,0.0,0.0,0.0,EXITOSO
8,Granja 20,9.0,CAMBOROUGH,1480.0,1335.0,NaN,5.0,1.0,115.0,14.000,6.0,4.0,0.0,0.0,0.0,NO_EXITOSO
9,Granja 20,10.0,CAMBOROUGH,1621.0,1476.0,NaN,5.0,1.0,114.0,13.666,6.0,5.0,0.0,0.0,0.0,EXITOSO

In [ ]:
# Se exporta el DataFrame procesado
df.to_csv('sabana_hembras_porcinas_procesado.csv', index=False)