# **Despliegue del Modelo Predictivo de Clasificación**

### **Por:**

*   Yasmin Judith Florez Zabala
*   John Jairo Sevilla Rodriguez
*   Yulexa Andrea Aragón Lemus

### **Ciclo de vida**
1. Carga del modelo
2. Carga de los datos futuros
3. Preparación de los datos futuros
4. Aplicación del modelo para la predicción

In [ ]:
# Se importan las librerías básicas
import pandas as pd # manipulacion dataframes
import numpy as np  # matrices y vectores
import matplotlib.pyplot as plt #gráfica

In [ ]:
# Se importa la librería pickle para cargar objetos almacenados
import pickle

# Nombre del archivo donde se encuentra guardado el modelo
filename = 'modelo-class-partos.pkl'

# Se cargan los objetos almacenados en el archivo:
# modelTree -> modelo entrenado
# labelencoder -> codificador de etiquetas utilizado
# variables -> nombres de las variables predictoras
modelrf, labelencoder, variables = pickle.load(open(filename, 'rb'))

In [ ]:
# Se cargan los datos futuros desde un archivo CSV que contiene las nuevas observaciones a predecir
#data = pd.read_csv("sabana_hembras_porcinas-datos_futuros.csv")
#data.head()

,NUMERO_PARTO,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,RETORNOS_ACUMULADOS
0,3,14.5,1,0
1,5,12.0,3,1
2,2,15.2,0,0
3,7,10.5,5,2
4,4,13.8,2,0

In [ ]:
#Interfaz gráfica
#Se crea interfaz gráfica con streamlit para captura de los datos

import streamlit as st

# Configuración de página
st.set_page_config(
    page_title="Predicción Parto Porcino",
    page_icon="🐷",
    layout="centered"
)

# Título con estilo
st.markdown("""
    <h1 style='text-align: center; color: #2E86AB;'>🐷 Predicción de Parto Exitoso</h1>
    <h4 style='text-align: center; color: #666;'>Hembras Porcinas — Modelo de Clasificación</h4>
    <hr>
""", unsafe_allow_html=True)

# Sección de entrada
st.markdown("### 📋 Ingrese los datos de la hembra")

col1, col2 = st.columns(2)

with col1:
    NUMERO_PARTO = st.slider(
        '🔢 Número de parto',
        min_value=2, max_value=19, value=4, step=1,
        help="Número de parto actual de la hembra"
    )
    TOTAL_MUERTOS_ANTERIORES = st.slider(
        '💀 Total muertos anteriores',
        min_value=0, max_value=35, value=2, step=1,
        help="Total de lechones muertos en partos anteriores"
    )

with col2:
    PROMEDIO_VIVOS_ANTERIORES = st.slider(
        '🐽 Promedio vivos anteriores',
        min_value=0.0, max_value=31.0, value=13.0, step=0.1,
        help="Promedio de lechones nacidos vivos en partos anteriores"
    )
    RETORNOS_ACUMULADOS = st.slider(
        '🔄 Retornos acumulados',
        min_value=0, max_value=9, value=0, step=1,
        help="Número de inseminaciones fallidas acumuladas"
    )

st.markdown("<hr>", unsafe_allow_html=True)

# Resumen de datos ingresados
st.markdown("### 📊 Resumen de datos ingresados")
col1, col2, col3, col4 = st.columns(4)
col1.metric("Nº Parto", NUMERO_PARTO)
col2.metric("Prom. Vivos", f"{PROMEDIO_VIVOS_ANTERIORES:.1f}")
col3.metric("Total Muertos", TOTAL_MUERTOS_ANTERIORES)
col4.metric("Retornos", RETORNOS_ACUMULADOS)

# DataFrame
datos = [[NUMERO_PARTO, PROMEDIO_VIVOS_ANTERIORES,
          TOTAL_MUERTOS_ANTERIORES, RETORNOS_ACUMULADOS]]
data = pd.DataFrame(datos, columns=[
    'NUMERO_PARTO', 'PROMEDIO_VIVOS_ANTERIORES',
    'TOTAL_MUERTOS_ANTERIORES', 'RETORNOS_ACUMULADOS'
])

# **Predicciones**

In [ ]:
# Se realizan las predicciones utilizando el modelo Árbol de Decisión entrenado

# predict() genera la clase predicha
# para cada registro del conjunto de datos futuro
Y_pred = modelrf.predict(data)

# Se muestran las predicciones obtenidas
print(Y_pred)

[0 1 0 1 0]

In [ ]:
data['PREDICCION'] = Y_pred
data['PREDICCION'] = data['PREDICCION'].map({0: 'EXITOSO', 1: 'NO EXITOSO'})
data.head()

,NUMERO_PARTO,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,RETORNOS_ACUMULADOS,PREDICCION
0,3,14.5,1,0,EXITOSO
1,5,12.0,3,1,NO EXITOSO
2,2,15.2,0,0,EXITOSO
3,7,10.5,5,2,NO EXITOSO
4,4,13.8,2,0,EXITOSO

In [ ]:
data

,NUMERO_PARTO,PROMEDIO_VIVOS_ANTERIORES,TOTAL_MUERTOS_ANTERIORES,RETORNOS_ACUMULADOS,PREDICCION
0,3,14.5,1,0,EXITOSO
1,5,12.0,3,1,NO EXITOSO
2,2,15.2,0,0,EXITOSO
3,7,10.5,5,2,NO EXITOSO
4,4,13.8,2,0,EXITOSO

In [ ]:
st.warning("El modelo tiene una precisión del 61.7%, lo que equivale a un error del 38.3%")